###VARIABLES###

#List of all IC OU Paths 
$OUSSAICs = 'OU=Contractors,OU=Six Sigma Employees,DC=sigma,DC=com'
$OUG100NICs = 'OU=ICs,OU=G100 Employees,DC=sigma,DC=com'
$OUG100CICs = 'OU=G100 Companies ICs,OU=G100 Companies,DC=sigma,DC=com'
$OUHLGICs = 'OU=HLG Contractors,OU=Highlantern Group Employees,DC=sigma,DC=com'
$OUTMGICs = 'OU=TMG ICs,OU=The Miles Group,DC=sigma,DC=com'
$OUMTRICs = 'OU=Mentore ICs,OU=Mentore,DC=sigma,DC=com'
$OUAsia = 'OU=Asia,OU=International Offices,DC=sigma,DC=com'

$ous = 'OU=Contractors,OU=Six Sigma Employees,DC=sigma,DC=com', 'OU=ICs,OU=G100 Employees,DC=sigma,DC=com', 'OU=G100 Companies ICs,OU=G100 Companies,DC=sigma,DC=com', 'OU=HLG Contractors,OU=Highlantern Group Employees,DC=sigma,DC=com', 'OU=TMG ICs,OU=The Miles Group,DC=sigma,DC=com', 'OU=Mentore ICs,OU=Mentore,DC=sigma,DC=com'

#Select AD Fields
$fields =  'DisplayName', 'Office', 'Company', 'Mail', 'Enabled'

#Current date to add to filename
$date = Get-Date
#Date Format
$date = $date.ToString('MM-dd-yy')

#Export File Path
$filepath = 'C:\exports\'
#Export File Name
$filename = 'Active_IC_List'

#SMTP Settings
$PSEmailServer = 'smtp-mail.outlook.com'
$emailfrom = 'Patrick Wilkes <patrick_wilkes@outlook.com>'
$emailto = 'Patrick Wilkes <pwilkes@1path.com>'
$emailbody = 'This message was autogenerated via PowerShell'
$emailuser = 'patrick_wilkes@outlook.com'
$emailpword = ConvertTo-SecureString -String 'P@tr1ck99' -AsPlainText -Force
$emailcredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $emailuser, $emailpword

###__________________________________________________________###

###PRE-REQs###

Import-Module ActiveDirectory

###__________________________________________________________###

###EXECUTION###

function Show-Menu
{
    param (
        [string]$Title = 'ACTIVE IC REPORT'
    )
    Clear-Host
    Write-Host "================ $Title ================"
    
    Write-Host "1: Press '1' to get IC report for G100C"
    Write-Host "2: Press '2' to get IC report for G100N"
    Write-Host "3: Press '3' to get IC report for TMG"
    Write-Host "4: Press '4' to get IC report for SSA"
    Write-Host "5: Press '5' to get IC report for HLG"
    Write-Host "6: Press '6' to get IC report for Mentore"
    Write-Host "7: Press '7' to get IC report for Asia"
    Write-Host "A: Press 'A' to get IC report for All Companies"
    Write-Host "Q: Press 'Q' to quit."
}
do
 {
     Show-Menu
     $selection = Read-Host "Please make a selection"
     switch ($selection)
     {
        '1' {
            $ou = $OUG100CICs
            $company = 'G100C'
            $export = $filepath, $company, '_', $filename, '_', $date, '.csv' -join ""
            $emailsubject = $company, ' ', 'Active IC Report' -join ""
            
            Get-ADUser -Filter * -SearchBase $ou -Properties $fields |
            Where-Object {$_.Enabled -notmatch 'False'} | Select-Object $fields | Sort-Object Company | Export-Csv $export -notypeinformation
            Send-MailMessage -from $emailfrom -to $emailto -Subject $emailsubject -Body $emailbody -attachments $export -smtpserver $PSEmailServer -credential $emailcredential -usessl
     }
        '2' {
            $ou = $OUG100NICs
            $company = 'G100N'
            $export = $filepath, $company, '_', $filename, '_', $date, '.csv' -join ""
            $emailsubject = $company, ' ', 'Active IC Report' -join ""
            
            Get-ADUser -Filter * -SearchBase $ou -Properties $fields |
            Where-Object {$_.Enabled -notmatch 'False'} | Select-Object $fields | Sort-Object Company | Export-Csv $export -notypeinformation
            Send-MailMessage -from $emailfrom -to $emailto -Subject $emailsubject -Body $emailbody -attachments $export -smtpserver $PSEmailServer -credential $emailcredential -usessl
     }  '3' {
            $ou = $OUTMGICs
            $company = 'TMG'
            $export = $filepath, $company, '_', $filename, '_', $date, '.csv' -join ""
            $emailsubject = $company, ' ', 'Active IC Report' -join ""
            
            Get-ADUser -Filter * -SearchBase $ou -Properties $fields |
            Where-Object {$_.Enabled -notmatch 'False'} | Select-Object $fields | Sort-Object Company | Export-Csv $export -notypeinformation
            Send-MailMessage -from $emailfrom -to $emailto -Subject $emailsubject -Body $emailbody -attachments $export -smtpserver $PSEmailServer -credential $emailcredential -usessl
     }  '4' {
            $ou = $OUSSAICs
            $company = 'SSA'
            $export = $filepath, $company, '_', $filename, '_', $date, '.csv' -join ""
            $emailsubject = $company, ' ', 'Active IC Report' -join ""
            
            Get-ADUser -Filter * -SearchBase $ou -Properties $fields |
            Where-Object {$_.Enabled -notmatch 'False'} | Select-Object $fields | Sort-Object Company | Export-Csv $export -notypeinformation
            Send-MailMessage -from $emailfrom -to $emailto -Subject $emailsubject -Body $emailbody -attachments $export -smtpserver $PSEmailServer -credential $emailcredential -usessl
     }  '5' {
            $ou = $OUHLGICs
            $company = 'HLG'
            $export = $filepath, $company, '_', $filename, '_', $date, '.csv' -join ""
            $emailsubject = $company, ' ', 'Active IC Report' -join ""
            
            Get-ADUser -Filter * -SearchBase $ou -Properties $fields |
            Where-Object {$_.Enabled -notmatch 'False'} | Select-Object $fields | Sort-Object Company | Export-Csv $export -notypeinformation
            Send-MailMessage -from $emailfrom -to $emailto -Subject $emailsubject -Body $emailbody -attachments $export -smtpserver $PSEmailServer -credential $emailcredential -usessl
     }  '6' {
            $ou = $OUMTRICs
            $company = 'Mentore'
            $export = $filepath, $company, '_', $filename, '_', $date, '.csv' -join ""
            $emailsubject = $company, ' ', 'Active IC Report' -join ""
            
            Get-ADUser -Filter * -SearchBase $ou -Properties $fields |
            Where-Object {$_.Enabled -notmatch 'False'} | Select-Object $fields | Sort-Object Company | Export-Csv $export -notypeinformation
            Send-MailMessage -from $emailfrom -to $emailto -Subject $emailsubject -Body $emailbody -attachments $export -smtpserver $PSEmailServer -credential $emailcredential -usessl
     }  '7' {
            $ou = $OUAsia
            $company = 'International - Asia'
            $export = $filepath, $company, '_', $filename, '_', $date, '.csv' -join ""
            $emailsubject = $company, ' ', 'Active IC Report' -join ""
            
            Get-ADUser -Filter * -SearchBase $ou -Properties $fields |
            Where-Object {$_.Enabled -notmatch 'False'} | Select-Object $fields | Sort-Object Company | Export-Csv $export -notypeinformation
            Send-MailMessage -from $emailfrom -to $emailto -Subject $emailsubject -Body $emailbody -attachments $export -smtpserver $PSEmailServer -credential $emailcredential -usessl

     }  'A' {
            $company = 'All Companies'
            $export = $filepath, $company, '_', $filename, '_', $date, '.csv' -join ""
            $emailsubject = $company, ' ', 'Active IC Report' -join ""

            $ous | ForEach {Get-ADUser -Filter * -SearchBase $_ -Properties $fields} |
            Where-Object {$_.Enabled -notmatch 'False'} | Select-Object $fields | Sort-Object Company | Export-Csv $export -notypeinformation
            Send-MailMessage -from $emailfrom -to $emailto -Subject $emailsubject -Body $emailbody -attachments $export -smtpserver $PSEmailServer -credential $emailcredential -usessl
     }
    }
}
until ($selection -eq 'q')
